# Generated by Django 3.1.5 on 2021-06-16 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='uploads')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date)),
                ('time', models.TimeField(default=datetime.time)),
            ],
        ),
    ]
