# Generated by Django 3.1.5 on 2021-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='link',
            new_name='link1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image5',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blog',
            name='link2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='link3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='link4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='link5',
            field=models.CharField(default='', max_length=200),
        ),
    ]
