# Generated by Django 3.1.5 on 2021-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210618_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description2',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
