# Generated by Django 3.1.5 on 2021-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorimage',
            field=models.ImageField(default='', upload_to='resources'),
        ),
    ]
