# Generated by Django 3.1.5 on 2021-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authorimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='resources'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
