# Generated by Django 3.1.5 on 2021-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210730_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description2',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
